#!/bin/bash

# Elastic API
kubectl port-forward svc/elastic-es-http -n elastic-system 9200 &
sleep 10
# Kibana UI
kubectl port-forward svc/elastic-kb-http -n elastic-system 5601 &
sleep 10
# Redis
kubectl port-forward svc/redis -n redis 6379 &
sleep 10
# minio
kubectl port-forward svc/minio -n minio 9000 &
sleep 10
# Scylla
kubectl port-forward svc/scylla-us-east-1-us-east-1a-0 -n scylla 9042 9142 9160 19042 19142 &
# Tunnel frontend and api ingress to localhost
# This command will block
sudo kubectl port-forward svc/ingress-nginx-controller -n ingress-nginx 80:80
#minikube tunnel

