//! The error class for the Thorium API

use aws_sdk_s3::error::SdkError;
use axum::Json;
use axum::http::StatusCode;
use axum::response::{IntoResponse, Response};
use std::fmt;
use tracing::{Level, event, span};
use utoipa::ToSchema;

use crate::models::InvalidEnum;
use crate::models::conversions::ConversionError;
use crate::utils::trace;

/// An error from the Thorium API
///
/// Only `Thorium` errors and errors from parsing user provided data may
/// expose their messages to users. All other variants are abstracted to a
/// generic error response while their full info is emitted as a tracing
/// event. Never embed the output of [`ApiError::msg`] or this types `Display`
/// impl into a user visible `Thorium` message as that could leak internal
/// info.
#[derive(Debug)]
pub enum ApiError {
    /// An error generated by Thorium itself
    ///
    /// These messages are always safe to expose to users.
    Thorium {
        /// The status code to return
        code: StatusCode,
        /// The error message to return
        msg: Option<String>,
    },
    /// A user tried to build an enum from an invalid value
    InvalidEnum(InvalidEnum),
    /// An error from converting user provided values
    Conversion(ConversionError),
    /// An error from parsing a Uuid
    Uuid(uuid::Error),
    /// An error from parsing an int
    ParseInt(std::num::ParseIntError),
    /// An error from parsing a float
    ParseFloat(std::num::ParseFloatError),
    /// An error from parsing a bool
    ParseBool(std::str::ParseBoolError),
    /// An error from parsing a timestamp/date
    ChronoParse(chrono::format::ParseError),
    /// An error from base64 decoding a string
    Base64Decode(base64::DecodeError),
    /// An error from casting bytes to a utf8 formatted str
    Utf8(std::str::Utf8Error),
    /// An error from parsing a URL
    UrlParse(url::ParseError),
    /// An error from casting an int
    TryFromInt(std::num::TryFromIntError),
    /// An error from extracting a multipart form
    Multipart(axum::extract::multipart::MultipartError),
    /// An error from deserializing query params
    SerdeQs(serde_qs::Error),
    /// An error from deserializing user provided yaml
    SerdeYaml(serde_norway::Error),
    /// An error from parsing a semver version
    Semver(semver::Error),
    /// An error from parsing an IP address
    AddrParse(std::net::AddrParseError),
    /// An error from parsing an enum variant with strum
    StrumParse(strum::ParseError),
    /// An error from parsing a country code
    CountryCode(isocountry::CountryCodeParseErr),
    /// An error from decoding a user uploaded CaRT file
    Cart(cart_rs::Error),
    /// An error from converting a value with serde
    Serde(serde_json::Error),
    /// An IO error
    IO(std::io::Error),
    /// An error from hashing with argon2
    Argon2(argon2::Error),
    /// An error from hashing a password with argon2
    PasswordHash(argon2::password_hash::Error),
    /// An error from talking to LDAP
    Ldap(ldap3::result::LdapError),
    /// An error from anyhow
    Anyhow(anyhow::Error),
    /// An error from an elastic client
    Elastic(elasticsearch::Error),
    /// An error from an elastic response
    ///
    /// This error is boxed because it is large enough to bloat the size of
    /// every `Result` containing an [`ApiError`].
    ElasticResponse(Box<elasticsearch::http::response::Error>),
    /// An error from the Redis backend
    Redis(bb8_redis::redis::RedisError),
    /// An error from executing a Scylla query
    ///
    /// This error is boxed because it is large enough to bloat the size of
    /// every `Result` containing an [`ApiError`].
    ScyllaExecution(Box<scylla::errors::ExecutionError>),
    /// An error from converting a Scylla query result into rows
    ///
    /// This error is boxed because it is large enough to bloat the size of
    /// every `Result` containing an [`ApiError`].
    ScyllaIntoRowsResult(Box<scylla::response::query_result::IntoRowsResultError>),
    /// An error from getting rows from a Scylla query result
    ScyllaRows(scylla::response::query_result::RowsError),
    /// An error from deserializing a Scylla row
    ScyllaDeserialization(scylla::deserialize::DeserializationError),
    /// An error from getting the first row of a Scylla query result
    ScyllaMaybeFirstRow(scylla::response::query_result::MaybeFirstRowError),
    /// An error from getting the next row from a Scylla pager
    ScyllaNextRow(scylla::client::pager::NextRowError),
    /// An error from executing a paged Scylla query
    ///
    /// This error is boxed because it is large enough to bloat the size of
    /// every `Result` containing an [`ApiError`].
    ScyllaPagerExecution(Box<scylla::errors::PagerExecutionError>),
    /// An error from type checking a Scylla row
    ScyllaTypeCheck(scylla::deserialize::TypeCheckError),
    /// An error from talking to S3
    S3 {
        /// The S3 action that failed
        action: &'static str,
        /// The error S3 returned
        error: Box<dyn std::error::Error + Send + Sync + 'static>,
    },
    /// An error from joining a tokio task
    TokioJoin(tokio::task::JoinError),
    /// An error from zipping a file
    Zip(zip::result::ZipError),
    /// An error from authenticating with OAuth
    OAuth(String),
}

impl ApiError {
    /// Creates a new Thorium error
    ///
    /// # Arguments
    ///
    /// * `code` - The status of the error response
    /// * `msg` - The message to put in the response
    #[must_use]
    pub fn new(code: StatusCode, msg: Option<String>) -> ApiError {
        ApiError::Thorium { code, msg }
    }

    /// Get the status code to return for this error
    #[must_use]
    pub fn status(&self) -> StatusCode {
        match self {
            // Thorium errors carry their own status code
            ApiError::Thorium { code, .. } => *code,
            // errors from parsing user provided data are bad requests
            ApiError::InvalidEnum(_)
            | ApiError::Conversion(_)
            | ApiError::Uuid(_)
            | ApiError::ParseInt(_)
            | ApiError::ParseFloat(_)
            | ApiError::ParseBool(_)
            | ApiError::ChronoParse(_)
            | ApiError::Base64Decode(_)
            | ApiError::Utf8(_)
            | ApiError::UrlParse(_)
            | ApiError::TryFromInt(_)
            | ApiError::Multipart(_)
            | ApiError::SerdeQs(_)
            | ApiError::SerdeYaml(_)
            | ApiError::Semver(_)
            | ApiError::AddrParse(_)
            | ApiError::StrumParse(_)
            | ApiError::CountryCode(_)
            | ApiError::Cart(_) => StatusCode::BAD_REQUEST,
            // failed OAuth authentications are unauthorized
            ApiError::OAuth(_) => StatusCode::UNAUTHORIZED,
            // all other errors are abstracted internal server errors
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }

    /// Get the full message for this error
    ///
    /// This may contain internal info so it must only be used for tracing
    /// events and logs and never in user visible messages. Use
    /// [`ApiError::public_msg`] when building responses instead.
    #[must_use]
    pub fn msg(&self) -> Option<String> {
        match self {
            ApiError::Thorium { msg, .. } => msg.clone(),
            ApiError::InvalidEnum(error) => Some(error.to_string()),
            ApiError::Conversion(error) => Some(format!("Unable to convert value {error:#?}")),
            ApiError::Uuid(error) => Some(format!("Failed cast to Uuid {error:#?}")),
            ApiError::ParseInt(error) => Some(format!("Failed cast to int {error:#?}")),
            ApiError::ParseFloat(error) => Some(format!("Failed cast to float {error:#?}")),
            ApiError::ParseBool(error) => Some(format!("Failed cast to bool {error:#?}")),
            ApiError::ChronoParse(error) => Some(format!("Failed to parse timestamp {error:#?}")),
            ApiError::Base64Decode(error) => {
                Some(format!("Failed to base64 decode string {error:#?}"))
            }
            ApiError::Utf8(error) => Some(format!("Failed to cast str to Utf8 {error:#?}")),
            ApiError::UrlParse(error) => Some(format!("URL parse error {error:#?}")),
            ApiError::TryFromInt(error) => Some(format!("Int casting error {error:#?}")),
            ApiError::Multipart(error) => {
                Some(format!("Failed to extract multipart form {error:#?}"))
            }
            ApiError::SerdeQs(error) => {
                Some(format!("Failed to deserialize query params {error:#?}"))
            }
            ApiError::SerdeYaml(error) => Some(format!("Failed to deserialize yaml {error:#?}")),
            ApiError::Semver(error) => Some(format!("Invalid semver version: {error:#?}")),
            ApiError::AddrParse(error) => Some(format!("Error parsing IP address: {error}")),
            ApiError::StrumParse(error) => Some(format!("Failed to parse variant: {error}")),
            ApiError::CountryCode(error) => {
                Some(format!("Failed to parse country code: {error}"))
            }
            ApiError::Cart(error) => Some(format!("Cart error {error:#?}")),
            ApiError::Serde(error) => Some(format!("Failed cast JsonValue to String {error:#?}")),
            ApiError::IO(error) => Some(format!("IO Error {error:#?}")),
            ApiError::Argon2(error) => Some(format!("Argon2 error {error:#?}")),
            ApiError::PasswordHash(error) => Some(format!("Argon2 password error {error:#?}")),
            ApiError::Ldap(error) => Some(format!("ldap error {error:#?}")),
            ApiError::Anyhow(error) => Some(format!("Anyhow error {error:#?}")),
            ApiError::Elastic(error) => Some(format!("Elasticsearch error {error:#?}")),
            ApiError::ElasticResponse(error) => Some(format!("Elasticsearch error {error:#?}")),
            ApiError::Redis(error) => Some(format!("Redis backend failure: {error:#?}")),
            ApiError::ScyllaExecution(error) => Some(format!("Scylla query error: {error:#?}")),
            ApiError::ScyllaIntoRowsResult(error) => {
                Some(format!("Scylla into rows error {error:#?}"))
            }
            ApiError::ScyllaRows(error) => Some(format!("Scylla rows error {error:#?}")),
            ApiError::ScyllaDeserialization(error) => {
                Some(format!("Scylla deserialization error {error:#?}"))
            }
            ApiError::ScyllaMaybeFirstRow(error) => {
                Some(format!("Scylla maybe first row error {error:#?}"))
            }
            ApiError::ScyllaNextRow(error) => Some(format!("Scylla next row error {error:#?}")),
            ApiError::ScyllaPagerExecution(error) => {
                Some(format!("Scylla pager execution error {error:#?}"))
            }
            ApiError::ScyllaTypeCheck(error) => {
                Some(format!("Scylla type check error {error:#?}"))
            }
            ApiError::S3 { action, error } => Some(format!("Failed to {action} {error:#?}")),
            ApiError::TokioJoin(error) => Some(format!("Tokio task failed to join: {error:#?}")),
            ApiError::Zip(error) => Some(format!("Failed to zip file: {error:#?}")),
            ApiError::OAuth(msg) => Some(msg.clone()),
        }
    }

    /// Get the message that is safe to expose to users for this error
    ///
    /// Only Thorium generated errors and errors from parsing user provided
    /// data return a message. All internal errors return `None` so their
    /// details are never leaked to users.
    #[must_use]
    pub fn public_msg(&self) -> Option<String> {
        match self {
            // Thorium generated messages are always safe to expose
            ApiError::Thorium { msg, .. } => msg.clone(),
            // errors from parsing user provided data are safe to expose
            ApiError::InvalidEnum(_)
            | ApiError::Conversion(_)
            | ApiError::Uuid(_)
            | ApiError::ParseInt(_)
            | ApiError::ParseFloat(_)
            | ApiError::ParseBool(_)
            | ApiError::ChronoParse(_)
            | ApiError::Base64Decode(_)
            | ApiError::Utf8(_)
            | ApiError::UrlParse(_)
            | ApiError::TryFromInt(_)
            | ApiError::Multipart(_)
            | ApiError::SerdeQs(_)
            | ApiError::SerdeYaml(_)
            | ApiError::Semver(_)
            | ApiError::AddrParse(_)
            | ApiError::StrumParse(_)
            | ApiError::CountryCode(_)
            | ApiError::Cart(_) => self.msg(),
            // all other errors are internal and must never be exposed
            _ => None,
        }
    }

    /// Get the kind of error as a str
    #[must_use]
    pub fn kind(&self) -> &'static str {
        match self {
            ApiError::Thorium { .. } => "Thorium",
            ApiError::InvalidEnum(_) => "InvalidEnum",
            ApiError::Conversion(_) => "Conversion",
            ApiError::Uuid(_) => "Uuid",
            ApiError::ParseInt(_) => "ParseInt",
            ApiError::ParseFloat(_) => "ParseFloat",
            ApiError::ParseBool(_) => "ParseBool",
            ApiError::ChronoParse(_) => "ChronoParse",
            ApiError::Base64Decode(_) => "Base64Decode",
            ApiError::Utf8(_) => "Utf8",
            ApiError::UrlParse(_) => "UrlParse",
            ApiError::TryFromInt(_) => "TryFromInt",
            ApiError::Multipart(_) => "Multipart",
            ApiError::SerdeQs(_) => "SerdeQs",
            ApiError::SerdeYaml(_) => "SerdeYaml",
            ApiError::Semver(_) => "Semver",
            ApiError::AddrParse(_) => "AddrParse",
            ApiError::StrumParse(_) => "StrumParse",
            ApiError::CountryCode(_) => "CountryCode",
            ApiError::Cart(_) => "Cart",
            ApiError::Serde(_) => "Serde",
            ApiError::IO(_) => "IO",
            ApiError::Argon2(_) => "Argon2",
            ApiError::PasswordHash(_) => "PasswordHash",
            ApiError::Ldap(_) => "Ldap",
            ApiError::Anyhow(_) => "Anyhow",
            ApiError::Elastic(_) => "Elastic",
            ApiError::ElasticResponse(_) => "ElasticResponse",
            ApiError::Redis(_) => "Redis",
            ApiError::ScyllaExecution(_) => "ScyllaExecution",
            ApiError::ScyllaIntoRowsResult(_) => "ScyllaIntoRowsResult",
            ApiError::ScyllaRows(_) => "ScyllaRows",
            ApiError::ScyllaDeserialization(_) => "ScyllaDeserialization",
            ApiError::ScyllaMaybeFirstRow(_) => "ScyllaMaybeFirstRow",
            ApiError::ScyllaNextRow(_) => "ScyllaNextRow",
            ApiError::ScyllaPagerExecution(_) => "ScyllaPagerExecution",
            ApiError::ScyllaTypeCheck(_) => "ScyllaTypeCheck",
            ApiError::S3 { .. } => "S3",
            ApiError::TokioJoin(_) => "TokioJoin",
            ApiError::Zip(_) => "Zip",
            ApiError::OAuth(_) => "OAuth",
        }
    }
}

impl fmt::Display for ApiError {
    /// Cast this error to either a string based on the message or the code
    ///
    /// This may contain internal info so it must never be embedded into a
    /// user visible `Thorium` message.
    ///
    /// # Arguments
    ///
    /// * `f` - The formatter that is being used
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self.msg() {
            Some(msg) => write!(f, "{msg}"),
            // if we have a status code then return that and the reason if one exists
            None => write!(f, "code {} - {}", self.status().as_u16(), self.status()),
        }
    }
}

// mark that this is an error struct
impl std::error::Error for ApiError {}

/// The JSON body returned for API errors
#[derive(Debug, Serialize, ToSchema)]
pub struct ApiErrorResponse {
    /// The error message if one can be exposed
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// The trace id for correlating this error with server side traces
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trace: Option<String>,
}

impl IntoResponse for ApiError {
    /// Allow Axum to build a response from error messages
    fn into_response(self) -> Response {
        // get our trace id
        let trace = trace::get_trace();
        // emit an event with the full info for this error
        let span = span!(Level::ERROR, "Error Message");
        event!(parent: &span, Level::ERROR, kind = self.kind(), msg = self.msg());
        // get the status code to return for this error
        let code = self.status();
        // get the message that is safe to expose to users
        let error = match self.public_msg() {
            // this message is safe to expose
            Some(msg) => Some(msg),
            // abstract internal server errors to a generic message
            None if code.is_server_error() => {
                Some("an internal server error occurred".to_owned())
            }
            // this error has no message to expose
            None => None,
        };
        // build our error response
        match (&error, &trace) {
            // we have no message or trace id so just return a status code
            (None, None) => code.into_response(),
            // return our error message and/or trace id
            _ => (code, Json(ApiErrorResponse { error, trace })).into_response(),
        }
    }
}

/// 400 bad request
#[macro_export]
macro_rules! bad {
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::BAD_REQUEST, Some($($msg)+)))}
}

/// 409 conflict
#[macro_export]
macro_rules! conflict {
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::CONFLICT, Some($($msg)+)))}
}

/// 404 not found
#[macro_export]
macro_rules! not_found {
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::NOT_FOUND, Some($($msg)+)))}
}

/// 404 not found without the Err wrap
#[macro_export]
macro_rules! not_found_unwrapped {
    ($($msg:tt)+) => {$crate::utils::ApiError::new(axum::http::status::StatusCode::NOT_FOUND, Some($($msg)+))}
}

/// 304 not modified
#[macro_export]
macro_rules! not_modified {
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::NOT_MODIFIED, Some($($msg)+)))}
}

/// 500 internal server error
#[macro_export]
macro_rules! internal_err {
    () => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::INTERNAL_SERVER_ERROR, None))};
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::INTERNAL_SERVER_ERROR, Some($($msg)+)))}
}

/// 500 internal server error without the Err wrap
#[macro_export]
macro_rules! internal_err_unwrapped {
    () => {$crate::utils::ApiError::new(axum::http::status::StatusCode::INTERNAL_SERVER_ERROR, None)};
    ($($msg:tt)+) => {$crate::utils::ApiError::new(axum::http::status::StatusCode::INTERNAL_SERVER_ERROR, Some($($msg)+))}
}

/// 503 service unavailable
#[macro_export]
macro_rules! unavailable {
    ($($msg:tt)+) => {Err($crate::utils::ApiError::new(axum::http::status::StatusCode::SERVICE_UNAVAILABLE, Some($($msg)+)))}
}

/// 401 unauthorized
#[macro_export]
macro_rules! unauthorized {
    () => {
        Err($crate::utils::ApiError::new(
            axum::http::status::StatusCode::UNAUTHORIZED,
            None,
        ))
    };
    ($msg:expr) => {
        Err($crate::utils::ApiError::new(
            axum::http::status::StatusCode::UNAUTHORIZED,
            Some($msg),
        ))
    };
}

/// 400 bad request without the Err wrap
#[macro_export]
macro_rules! bad_internal {
    ($($msg:tt)+) => {$crate::utils::ApiError::new(axum::http::status::StatusCode::BAD_REQUEST, Some($($msg)+))}
}

/// 429 rate limit
#[macro_export]
macro_rules! too_many_requests{
    ($($msg:tt)+) => {$crate::utils::ApiError::new(axum::http::status::StatusCode::TOO_MANY_REQUESTS, Some($($msg)+))}
}

impl From<InvalidEnum> for ApiError {
    /// Cast an invalid enum error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The invalid enum error to convert to an ApiError
    fn from(error: InvalidEnum) -> Self {
        ApiError::InvalidEnum(error)
    }
}

impl From<ConversionError> for ApiError {
    /// Cast a conversion error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The conversion error to convert to an ApiError
    fn from(error: ConversionError) -> Self {
        ApiError::Conversion(error)
    }
}

impl From<uuid::Error> for ApiError {
    /// Cast a uuid error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The uuid error to convert to an ApiError
    fn from(error: uuid::Error) -> Self {
        ApiError::Uuid(error)
    }
}

impl From<serde_json::Error> for ApiError {
    /// Cast a serde_json error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The serde_json error to convert to an ApiError
    fn from(error: serde_json::Error) -> Self {
        ApiError::Serde(error)
    }
}

impl From<std::num::ParseIntError> for ApiError {
    /// Cast an int parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The int parsing error to convert to an ApiError
    fn from(error: std::num::ParseIntError) -> Self {
        ApiError::ParseInt(error)
    }
}

impl From<std::num::ParseFloatError> for ApiError {
    /// Cast a float parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The float parsing error to convert to an ApiError
    fn from(error: std::num::ParseFloatError) -> Self {
        ApiError::ParseFloat(error)
    }
}

impl From<std::str::ParseBoolError> for ApiError {
    /// Cast a bool parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The bool parsing error to convert to an ApiError
    fn from(error: std::str::ParseBoolError) -> Self {
        ApiError::ParseBool(error)
    }
}

impl From<std::io::Error> for ApiError {
    /// Cast an IO error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The IO error to convert to an ApiError
    fn from(error: std::io::Error) -> Self {
        ApiError::IO(error)
    }
}

impl From<chrono::format::ParseError> for ApiError {
    /// Cast a timestamp parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The timestamp parsing error to convert to an ApiError
    fn from(error: chrono::format::ParseError) -> Self {
        ApiError::ChronoParse(error)
    }
}

impl From<base64::DecodeError> for ApiError {
    /// Cast a base64 decoding error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The base64 decoding error to convert to an ApiError
    fn from(error: base64::DecodeError) -> Self {
        ApiError::Base64Decode(error)
    }
}

impl From<std::str::Utf8Error> for ApiError {
    /// Cast a utf8 casting error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The utf8 casting error to convert to an ApiError
    fn from(error: std::str::Utf8Error) -> Self {
        ApiError::Utf8(error)
    }
}

impl From<argon2::Error> for ApiError {
    /// Cast an argon2 error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The argon2 error to convert to an ApiError
    fn from(error: argon2::Error) -> Self {
        ApiError::Argon2(error)
    }
}

impl From<argon2::password_hash::Error> for ApiError {
    /// Cast an argon2 password hash error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The argon2 password hash error to convert to an ApiError
    fn from(error: argon2::password_hash::Error) -> Self {
        ApiError::PasswordHash(error)
    }
}

impl From<ldap3::result::LdapError> for ApiError {
    /// Cast an ldap error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The ldap error to convert to an ApiError
    fn from(error: ldap3::result::LdapError) -> Self {
        ApiError::Ldap(error)
    }
}

impl From<anyhow::Error> for ApiError {
    /// Cast an anyhow error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The anyhow error to convert to an ApiError
    fn from(error: anyhow::Error) -> Self {
        ApiError::Anyhow(error)
    }
}

impl From<cart_rs::Error> for ApiError {
    /// Cast a CaRT error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The CaRT error to convert to an ApiError
    fn from(error: cart_rs::Error) -> Self {
        ApiError::Cart(error)
    }
}

impl From<url::ParseError> for ApiError {
    /// Cast a URL parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The URL parsing error to convert to an ApiError
    fn from(error: url::ParseError) -> Self {
        ApiError::UrlParse(error)
    }
}

impl From<std::num::TryFromIntError> for ApiError {
    /// Cast an int casting error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The int casting error to convert to an ApiError
    fn from(error: std::num::TryFromIntError) -> Self {
        ApiError::TryFromInt(error)
    }
}

impl From<elasticsearch::Error> for ApiError {
    /// Cast an elasticsearch error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The elasticsearch error to convert to an ApiError
    fn from(error: elasticsearch::Error) -> Self {
        ApiError::Elastic(error)
    }
}

impl From<elasticsearch::http::response::Error> for ApiError {
    /// Cast an elasticsearch response error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The elasticsearch response error to convert to an ApiError
    fn from(error: elasticsearch::http::response::Error) -> Self {
        ApiError::ElasticResponse(Box::new(error))
    }
}

impl From<scylla::response::query_result::IntoRowsResultError> for ApiError {
    /// Cast a Scylla into rows error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla into rows error to convert to an ApiError
    fn from(error: scylla::response::query_result::IntoRowsResultError) -> Self {
        ApiError::ScyllaIntoRowsResult(Box::new(error))
    }
}

impl From<scylla::response::query_result::RowsError> for ApiError {
    /// Cast a Scylla rows error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla rows error to convert to an ApiError
    fn from(error: scylla::response::query_result::RowsError) -> Self {
        ApiError::ScyllaRows(error)
    }
}

impl From<scylla::deserialize::DeserializationError> for ApiError {
    /// Cast a Scylla deserialization error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla deserialization error to convert to an ApiError
    fn from(error: scylla::deserialize::DeserializationError) -> Self {
        ApiError::ScyllaDeserialization(error)
    }
}

impl From<scylla::response::query_result::MaybeFirstRowError> for ApiError {
    /// Cast a Scylla maybe first row error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla maybe first row error to convert to an ApiError
    fn from(error: scylla::response::query_result::MaybeFirstRowError) -> Self {
        ApiError::ScyllaMaybeFirstRow(error)
    }
}

impl From<scylla::client::pager::NextRowError> for ApiError {
    /// Cast a Scylla next row error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla next row error to convert to an ApiError
    fn from(error: scylla::client::pager::NextRowError) -> Self {
        ApiError::ScyllaNextRow(error)
    }
}

impl From<scylla::errors::PagerExecutionError> for ApiError {
    /// Cast a Scylla pager execution error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla pager execution error to convert to an ApiError
    fn from(error: scylla::errors::PagerExecutionError) -> Self {
        ApiError::ScyllaPagerExecution(Box::new(error))
    }
}

impl From<scylla::deserialize::TypeCheckError> for ApiError {
    /// Cast a Scylla type check error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The Scylla type check error to convert to an ApiError
    fn from(error: scylla::deserialize::TypeCheckError) -> Self {
        ApiError::ScyllaTypeCheck(error)
    }
}

impl From<axum::extract::multipart::MultipartError> for ApiError {
    /// Cast a multipart form error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The multipart form error to convert to an ApiError
    fn from(error: axum::extract::multipart::MultipartError) -> Self {
        ApiError::Multipart(error)
    }
}

impl From<serde_qs::Error> for ApiError {
    /// Cast a query params error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The query params error to convert to an ApiError
    fn from(error: serde_qs::Error) -> Self {
        ApiError::SerdeQs(error)
    }
}

impl From<serde_norway::Error> for ApiError {
    /// Cast a yaml error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The yaml error to convert to an ApiError
    fn from(error: serde_norway::Error) -> Self {
        ApiError::SerdeYaml(error)
    }
}

impl From<semver::Error> for ApiError {
    /// Cast a semver error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The semver error to convert to an ApiError
    fn from(error: semver::Error) -> Self {
        ApiError::Semver(error)
    }
}

impl From<aws_sdk_s3::operation::head_object::HeadObjectError> for ApiError {
    /// Cast an S3 head object error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 head object error to convert to an ApiError
    fn from(error: aws_sdk_s3::operation::head_object::HeadObjectError) -> Self {
        ApiError::S3 {
            action: "check if an object exists",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::head_object::HeadObjectError>> for ApiError {
    /// Cast an S3 head object error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 head object error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::head_object::HeadObjectError>) -> Self {
        ApiError::S3 {
            action: "check if an object exists",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::list_objects_v2::ListObjectsV2Error>> for ApiError {
    /// Cast an S3 list objects error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 list objects error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::list_objects_v2::ListObjectsV2Error>) -> Self {
        ApiError::S3 {
            action: "list objects from s3",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadError>>
    for ApiError
{
    /// Cast an S3 create multipart upload error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 create multipart upload error to convert to an ApiError
    fn from(
        error: SdkError<aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadError>,
    ) -> Self {
        ApiError::S3 {
            action: "create multipart upload",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::upload_part::UploadPartError>> for ApiError {
    /// Cast an S3 upload part error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 upload part error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::upload_part::UploadPartError>) -> Self {
        ApiError::S3 {
            action: "upload multipart chunk",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadError>>
    for ApiError
{
    /// Cast an S3 complete multipart upload error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 complete multipart upload error to convert to an ApiError
    fn from(
        error: SdkError<
            aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadError,
        >,
    ) -> Self {
        ApiError::S3 {
            action: "complete multipart upload",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::abort_multipart_upload::AbortMultipartUploadError>>
    for ApiError
{
    /// Cast an S3 abort multipart upload error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 abort multipart upload error to convert to an ApiError
    fn from(
        error: SdkError<aws_sdk_s3::operation::abort_multipart_upload::AbortMultipartUploadError>,
    ) -> Self {
        ApiError::S3 {
            action: "abort multipart upload",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::put_object::PutObjectError>> for ApiError {
    /// Cast an S3 put object error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 put object error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::put_object::PutObjectError>) -> Self {
        ApiError::S3 {
            action: "upload object to s3",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::get_object::GetObjectError>> for ApiError {
    /// Cast an S3 get object error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 get object error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::get_object::GetObjectError>) -> Self {
        ApiError::S3 {
            action: "get object from s3",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::delete_object::DeleteObjectError>> for ApiError {
    /// Cast an S3 delete object error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 delete object error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::delete_object::DeleteObjectError>) -> Self {
        ApiError::S3 {
            action: "delete object from s3",
            error: Box::new(error),
        }
    }
}

impl From<SdkError<aws_sdk_s3::operation::delete_objects::DeleteObjectsError>> for ApiError {
    /// Cast an S3 delete objects error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The S3 delete objects error to convert to an ApiError
    fn from(error: SdkError<aws_sdk_s3::operation::delete_objects::DeleteObjectsError>) -> Self {
        ApiError::S3 {
            action: "delete objects from s3",
            error: Box::new(error),
        }
    }
}

impl From<tokio::task::JoinError> for ApiError {
    /// Cast a tokio join error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The tokio join error to convert to an ApiError
    fn from(error: tokio::task::JoinError) -> Self {
        ApiError::TokioJoin(error)
    }
}

impl From<zip::result::ZipError> for ApiError {
    /// Cast a zip error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The zip error to convert to an ApiError
    fn from(error: zip::result::ZipError) -> Self {
        ApiError::Zip(error)
    }
}

impl From<std::net::AddrParseError> for ApiError {
    /// Cast an IP address parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The IP address parsing error to convert to an ApiError
    fn from(error: std::net::AddrParseError) -> Self {
        ApiError::AddrParse(error)
    }
}

impl From<strum::ParseError> for ApiError {
    /// Cast a strum parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The strum parsing error to convert to an ApiError
    fn from(error: strum::ParseError) -> Self {
        ApiError::StrumParse(error)
    }
}

impl From<isocountry::CountryCodeParseErr> for ApiError {
    /// Cast a country code parsing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The country code parsing error to convert to an ApiError
    fn from(error: isocountry::CountryCodeParseErr) -> Self {
        ApiError::CountryCode(error)
    }
}

/// This conversion should never actually happen as its for infallible
///
/// But its better to have this code here then just unwrap in a bunch of places in case
/// an infallible function becomes fallible in the future.
impl From<std::convert::Infallible> for ApiError {
    /// Cast an infallible error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `infallible` - The infallible error that can never exist
    fn from(infallible: std::convert::Infallible) -> Self {
        // this error can never be built so this can never be reached
        match infallible {}
    }
}

/// Convert an OAuth config error to unauthorized
impl From<openidconnect::ConfigurationError> for ApiError {
    /// Cast an OAuth configuration error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The OAuth configuration error to convert to an ApiError
    fn from(error: openidconnect::ConfigurationError) -> Self {
        ApiError::OAuth(format!("OAuth configuration error: {error:#?}"))
    }
}

/// Conert an OAuth token error to unauthorized
impl
    From<
        openidconnect::RequestTokenError<
            openidconnect::HttpClientError<reqwest::Error>,
            openidconnect::StandardErrorResponse<openidconnect::core::CoreErrorResponseType>,
        >,
    > for ApiError
{
    /// Cast an OAuth token request error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The OAuth token request error to convert to an ApiError
    fn from(
        error: openidconnect::RequestTokenError<
            openidconnect::HttpClientError<reqwest::Error>,
            openidconnect::StandardErrorResponse<openidconnect::core::CoreErrorResponseType>,
        >,
    ) -> Self {
        ApiError::OAuth(format!("OAuth token request error: {error:#?}"))
    }
}

/// Convert an OAuth claims verification error to unauthorized
impl From<openidconnect::ClaimsVerificationError> for ApiError {
    /// Cast an OAuth claims verification error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The OAuth claims verification error to convert to an ApiError
    fn from(error: openidconnect::ClaimsVerificationError) -> Self {
        ApiError::OAuth(format!("OAuth claims verification error: {error:#?}"))
    }
}

/// Convert an OAuth signature verification error to unauthorized
impl From<openidconnect::SignatureVerificationError> for ApiError {
    /// Cast an OAuth signature verification error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The OAuth signature verification error to convert to an ApiError
    fn from(error: openidconnect::SignatureVerificationError) -> Self {
        ApiError::OAuth(format!("OAuth signature verification error: {error:#?}"))
    }
}

/// Convert an OAuth signing error to unauthorized
impl From<openidconnect::SigningError> for ApiError {
    /// Cast an OAuth signing error into an ApiError
    ///
    /// # Arguments
    ///
    /// * `error` - The OAuth signing error to convert to an ApiError
    fn from(error: openidconnect::SigningError) -> Self {
        ApiError::OAuth(format!("OAuth signing error: {error:#?}"))
    }
}

/// Convert [`ApiError`] into an [`rmcp::ErrorData`]
impl From<ApiError> for rmcp::ErrorData {
    /// Cast an ApiError into an rmcp error
    ///
    /// # Arguments
    ///
    /// * `error` - The ApiError to convert to an rmcp error
    fn from(error: ApiError) -> Self {
        // emit an event with the full info since this path skips into_response
        let span = span!(Level::ERROR, "Error Message");
        event!(parent: &span, Level::ERROR, kind = error.kind(), msg = error.msg());
        // get the status code for this error
        let status = error.status();
        // get the message that is safe to expose or fall back to a generic one
        let message = match error.public_msg() {
            // this message is safe to expose
            Some(msg) => msg,
            // abstract internal server errors to a generic message
            None if status.is_server_error() => "an internal server error occurred".to_owned(),
            // this error has no message to expose
            None => "Unknown Error".to_owned(),
        };
        // map our return code to an rmcp error code
        let code = match status {
            StatusCode::NOT_FOUND => rmcp::model::ErrorCode::RESOURCE_NOT_FOUND,
            StatusCode::BAD_REQUEST => rmcp::model::ErrorCode::INVALID_REQUEST,
            _ => rmcp::model::ErrorCode::INTERNAL_ERROR,
        };
        // build our rmcp error
        rmcp::ErrorData {
            code,
            message: message.into(),
            data: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Get the body of a response as a string
    ///
    /// # Arguments
    ///
    /// * `response` - The response to extract a body from
    async fn body_string(response: Response) -> String {
        // read the full body of this response
        let bytes = axum::body::to_bytes(response.into_body(), usize::MAX)
            .await
            .expect("Failed to read response body");
        // cast our body to a string
        String::from_utf8(bytes.to_vec()).expect("Response body was not utf8")
    }

    /// Build a Redis error containing a secret internal detail
    fn redis_error() -> bb8_redis::redis::RedisError {
        bb8_redis::redis::RedisError::from((
            bb8_redis::redis::ErrorKind::IoError,
            "io error",
            "secret internal detail".to_owned(),
        ))
    }

    #[tokio::test]
    async fn thorium_errors_expose_their_message() {
        // build a Thorium generated error
        let error: Result<(), ApiError> = bad!("Corn must be shucked!".to_owned());
        // build a response from this error
        let response = error.unwrap_err().into_response();
        // make sure the status code and message are exposed
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        assert!(body_string(response).await.contains("Corn must be shucked!"));
    }

    #[tokio::test]
    async fn parse_errors_expose_their_message() {
        // build an error from parsing user provided data
        let error = ApiError::from(uuid::Uuid::try_parse("not-a-uuid").unwrap_err());
        // build a response from this error
        let response = error.into_response();
        // make sure the status code and message are exposed
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        assert!(body_string(response).await.contains("Failed cast to Uuid"));
    }

    #[tokio::test]
    async fn redis_errors_are_hidden() {
        // build an internal Redis error with a secret detail
        let error = ApiError::from(redis_error());
        // make sure the full info is still available for tracing events
        assert!(error.msg().unwrap().contains("secret internal detail"));
        // build a response from this error
        let response = error.into_response();
        // make sure this error was abstracted to a generic 500
        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);
        let body = body_string(response).await;
        assert!(body.contains("an internal server error occurred"));
        assert!(!body.contains("secret internal detail"));
    }

    #[tokio::test]
    async fn serde_errors_are_hidden() {
        // build an internal serde error
        let error = ApiError::from(serde_json::from_str::<u32>("bad json").unwrap_err());
        // build a response from this error
        let response = error.into_response();
        // make sure this error was abstracted to a generic 500
        assert_eq!(response.status(), StatusCode::INTERNAL_SERVER_ERROR);
        let body = body_string(response).await;
        assert!(body.contains("an internal server error occurred"));
        assert!(!body.contains("bad json"));
    }

    #[tokio::test]
    async fn oauth_errors_are_bare_401s() {
        // build an internal OAuth error with a secret detail
        let error = ApiError::OAuth("secret oauth detail".to_owned());
        // build a response from this error
        let response = error.into_response();
        // make sure this error is a 401 with no error message
        assert_eq!(response.status(), StatusCode::UNAUTHORIZED);
        assert!(!body_string(response).await.contains("secret oauth detail"));
    }

    #[test]
    fn accessors_follow_the_exposure_policy() {
        // build one error of each exposure class
        let thorium = ApiError::new(StatusCode::CONFLICT, Some("already exists".to_owned()));
        let parse = ApiError::from(uuid::Uuid::try_parse("not-a-uuid").unwrap_err());
        let hidden = ApiError::from(redis_error());
        let oauth = ApiError::OAuth("secret oauth detail".to_owned());
        // make sure the status codes are correct
        assert_eq!(thorium.status(), StatusCode::CONFLICT);
        assert_eq!(parse.status(), StatusCode::BAD_REQUEST);
        assert_eq!(hidden.status(), StatusCode::INTERNAL_SERVER_ERROR);
        assert_eq!(oauth.status(), StatusCode::UNAUTHORIZED);
        // make sure only safe messages are exposed
        assert_eq!(thorium.public_msg(), Some("already exists".to_owned()));
        assert!(parse.public_msg().is_some());
        assert_eq!(hidden.public_msg(), None);
        assert_eq!(oauth.public_msg(), None);
        // make sure the kinds are correct
        assert_eq!(thorium.kind(), "Thorium");
        assert_eq!(parse.kind(), "Uuid");
        assert_eq!(hidden.kind(), "Redis");
        assert_eq!(oauth.kind(), "OAuth");
    }

    #[test]
    fn rmcp_errors_follow_the_exposure_policy() {
        // build an internal Redis error with a secret detail
        let hidden = rmcp::ErrorData::from(ApiError::from(redis_error()));
        // make sure this error was abstracted to a generic internal error
        assert_eq!(hidden.code, rmcp::model::ErrorCode::INTERNAL_ERROR);
        assert_eq!(hidden.message, "an internal server error occurred");
        // build a Thorium generated error
        let thorium: Result<(), ApiError> = bad!("Corn must be shucked!".to_owned());
        let exposed = rmcp::ErrorData::from(thorium.unwrap_err());
        // make sure the message is exposed for Thorium errors
        assert_eq!(exposed.code, rmcp::model::ErrorCode::INVALID_REQUEST);
        assert_eq!(exposed.message, "Corn must be shucked!");
    }
}
